spring:
  application:
    name: syncPlayer1
server:
  port: 8080

game:
  settings:
    sync:
      default2ndPlayerAddress: 'http://localhost:9090'
      healthEndpoint: '/go3/api/v1/health'
      playEndpoint: '/go3/api/v1/play'

    maxRandom: 10000
