spring:
  application:
    name: asyncPlayer2

  profiles:
    include: async

server:
  port: 9191

game:
  settings:
    default2ndPlayerAddress: player1

    async:
      url: tcp://127.0.0.1:61616
      topic: player2
