spring:
  application:
    name: syncPlayer2
server:
  port: 9090

game:
  settings:
    sync:
      default2ndPlayerAddress: 'http://localhost:8080'
      healthEndpoint: '/go3/api/v1/health'
      playEndpoint: '/go3/api/v1/play'
