spring:

  application:
    name: asyncPlayer1

  profiles:
    include: async

server:
  port: 8181
game:
  settings:
    default2ndPlayerAddress: player2

    async:
      url: tcp://127.0.0.1:61616
      topic: player1
