spring:
  application:
    name: player1
server:
  port: 8080

game:
  settings:
    sync:
      default2ndPlayerAddress: 'http://localhost:9090'
      healthEndpoint: '/go3/api/v1/health'
      playEndpoint: '/go3/api/v1/play'

    async:
      brokerAddress: '127.0.0.1:8161'
      topic: 'player1'

    maxRandom: 10000
